# cFE NAME: CFE_ES_AppInfo
# ROS topic: cfe_es_appinfo
uint32 resource_id
uint32 type
string name
string entry_point
string file_name
uint32 stack_size
uint32 addresses_are_valid
uint32 code_address
uint32 code_size
uint32 data_address
uint32 data_size
uint32 bss_address
uint32 bss_size
uint32 start_address
uint8 exception_action
uint8 spare0
uint16 priority
uint32 main_task_id
uint32 execution_counter
string main_task_name
uint32 num_of_child_tasks
