# cFE NAME: SB STATs Tlm
# FILE: cfe-sb-stats-tlm.txt
int32 seq
uint32 msgidsinuse
uint32 peakmsgidsinuse
uint32 maxmsgidsallowed
uint32 pipesinuse
uint32 peakpipesinuse
uint32 maxpipesallowed
uint32 meminuse
uint32 peakmeminuse
uint32 maxmemallowed
uint32 subscriptionsinuse
uint32 peaksubscriptionsinuse
uint32 maxsubscriptionsallowed
uint32 sbbuffersinuse
uint32 peaksbbuffersinuse
uint32 maxpipedepthallowed
