cfe_bridge:
  ros__parameters:
    plugin_name: cfe_plugin.cfe_plugin
    plugin_params:
      juicer_db: ["cfs_bootes-rc1-dev83_TL.sqlite"]
      commandPort: 1234
      commandHost: "127.0.0.7"
      telemetryPort: 1235
      commands: ["CFEESAppNameCmd", "CFEESDeleteCDSCmd", "CFEESDumpCDSRegistryCmd", "CFEESFileNameCmd", "CFEESNoArgsCmd", "CFEESOverWriteSysLogCmd", "CFEESReloadAppCmd", "CFEESRestartCmd", "CFEESSendMemPoolStatsCmd", "CFEESSetMaxPRCountCmd", "CFEESSetPerfFilterMaskCmd", "CFEESSetPerfTriggerMaskCmd", "CFEESStartApp", "CFEESStartPerfDataCmd", "CFEESStopPerfDataCmd", "CFEEVSAppNameBitMaskCmd", "CFEEVSAppNameCmd", "CFEEVSAppNameEventIDCmd", "CFEEVSAppNameEventIDMaskCmd", "CFEEVSBitMaskCmd", "CFEEVSNoArgsCmd", "CFEEVSSetEventFormatModeCmd", "CFEEVSSetLogModeCmd", "CFEEVSWriteAppDataFileCmd", "CFEEVSWriteLogDataFileCmd", "CFESBRouteCmd", "CFESBWriteFileInfoCmd", "CFETBLAbortLoadCmd", "CFETBLActivateCmd", "CFETBLDeleteCDSCmd", "CFETBLDumpCmd", "CFETBLDumpRegistryCmd", "CFETBLLoadCmd", "CFETBLNoArgsCmd", "CFETBLNotifyCmd", "CFETBLSendRegistryCmd", "CFETBLValidateCmd", "CFETIMENoArgsCmd", "CFETIMEOneHzAdjustmentCmd", "CFETIMESetLeapSecondsCmd", "CFETIMESetSignalCmd", "CFETIMESetSourceCmd", "CFETIMESetStateCmd", "CFETIMETimeCmd", "CFETIMEToneDataCmd", "CILABNoArgsCmdt", "ROSAPPNoArgsCmdt", "SAMPLEAPPNoArgsCmdt", "SCHLABStateEntryt", "TOLABAddPacketCmdt", "TOLABEnableOutputCmdt", "TOLABNoArgsCmdt", "TOLABRemovePacketCmdt"]
      
      telemetry: ["CFEESOneAppTlm", "CFEESMemStatsTlm", "CFEESHousekeepingTlm", "CFEEVSLongEventTlm", "CFEEVSHousekeepingTlm", "CFEEVSShortEventTlm", "CFESBHousekeepingTlm", "CFESBStatsTlm", "CFESBAllSubscriptionsTlm", "CFESBSingleSubscriptionTlm", "CFETBLHousekeepingTlm", "CFETBLTableRegistryTlm", "CFETIMEHousekeepingTlm", "CFETIMEDiagnosticTlm"]
      command_data:
        CFEESAppNameCmd:
          structure: CFEESAppNameCmd
          cfe_mid: '0x1200'
          cmd_code: 3  
        CFEESDeleteCDSCmd:
          structure: CFEESDeleteCDSCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEESDumpCDSRegistryCmd:
          structure: CFEESDumpCDSRegistryCmd
          cfe_mid: '0x1200'
          cmd_code: 2  
        CFEESFileNameCmd:
          structure: CFEESFileNameCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEESNoArgsCmd:
          structure: CFEESNoArgsCmd
          cfe_mid: '0x1200'
          cmd_code: 1  
        CFEESOverWriteSysLogCmd:
          structure: CFEESOverWriteSysLogCmd
          cfe_mid: '0x1200'
          cmd_code: 1  
        CFEESReloadAppCmd:
          structure: CFEESReloadAppCmd
          cfe_mid: '0x1200'
          cmd_code: 4  
        CFEESRestartCmd:
          structure: CFEESRestartCmd
          cfe_mid: '0x1200'
          cmd_code: 2  
        CFEESSendMemPoolStatsCmd:
          structure: CFEESSendMemPoolStatsCmd
          cfe_mid: '0x1200'
          cmd_code: 1  
        CFEESSetMaxPRCountCmd:
          structure: CFEESSetMaxPRCountCmd
          cfe_mid: '0x1200'
          cmd_code: 5  
        CFEESSetPerfFilterMaskCmd:
          structure: CFEESSetPerfFilterMaskCmd
          cfe_mid: '0x1200'
          cmd_code: 2  
        CFEESSetPerfTriggerMaskCmd:
          structure: CFEESSetPerfTriggerMaskCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEESStartApp:
          structure: CFEESStartApp
          cfe_mid: '0x1200'
          cmd_code: 2  
        CFEESStartPerfDataCmd:
          structure: CFEESStartPerfDataCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEESStopPerfDataCmd:
          structure: CFEESStopPerfDataCmd
          cfe_mid: '0x1200'
          cmd_code: 1  
        CFEEVSAppNameBitMaskCmd:
          structure: CFEEVSAppNameBitMaskCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSAppNameCmd:
          structure: CFEEVSAppNameCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSAppNameEventIDCmd:
          structure: CFEEVSAppNameEventIDCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSAppNameEventIDMaskCmd:
          structure: CFEEVSAppNameEventIDMaskCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSBitMaskCmd:
          structure: CFEEVSBitMaskCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSNoArgsCmd:
          structure: CFEEVSNoArgsCmd
          cfe_mid: '0x1200'
          cmd_code: 5  
        CFEEVSSetEventFormatModeCmd:
          structure: CFEEVSSetEventFormatModeCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFEEVSSetLogModeCmd:
          structure: CFEEVSSetLogModeCmd
          cfe_mid: '0x1200'
          cmd_code: 4  
        CFEEVSWriteAppDataFileCmd:
          structure: CFEEVSWriteAppDataFileCmd
          cfe_mid: '0x1200'
          cmd_code: 6  
        CFEEVSWriteLogDataFileCmd:
          structure: CFEEVSWriteLogDataFileCmd
          cfe_mid: '0x1200'
          cmd_code: 3  
        CFESBRouteCmd:
          structure: CFESBRouteCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFESBWriteFileInfoCmd:
          structure: CFESBWriteFileInfoCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLAbortLoadCmd:
          structure: CFETBLAbortLoadCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLActivateCmd:
          structure: CFETBLActivateCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLDeleteCDSCmd:
          structure: CFETBLDeleteCDSCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLDumpCmd:
          structure: CFETBLDumpCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLDumpRegistryCmd:
          structure: CFETBLDumpRegistryCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLLoadCmd:
          structure: CFETBLLoadCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLNoArgsCmd:
          structure: CFETBLNoArgsCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLNotifyCmd:
          structure: CFETBLNotifyCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLSendRegistryCmd:
          structure: CFETBLSendRegistryCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETBLValidateCmd:
          structure: CFETBLValidateCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMENoArgsCmd:
          structure: CFETIMENoArgsCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMEOneHzAdjustmentCmd:
          structure: CFETIMEOneHzAdjustmentCmd
          cfe_mid: '0x1200'
          cmd_code: 0
        CFETIMESetLeapSecondsCmd:
          structure: CFETIMESetLeapSecondsCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMESetSignalCmd:
          structure: CFETIMESetSignalCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMESetSourceCmd:
          structure: CFETIMESetSourceCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMESetStateCmd:
          structure: CFETIMESetStateCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMETimeCmd:
          structure: CFETIMETimeCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CFETIMEToneDataCmd:
          structure: CFETIMEToneDataCmd
          cfe_mid: '0x1200'
          cmd_code: 0  
        CILABNoArgsCmdt:
          structure: CILABNoArgsCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
        ROSAPPNoArgsCmdt:
          structure: ROSAPPNoArgsCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
        SAMPLEAPPNoArgsCmdt:
          structure: SAMPLEAPPNoArgsCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
        SCHLABStateEntryt:
          structure: SCHLABStateEntryt
          cfe_mid: '0x1200'
          cmd_code: 0  
        TOLABAddPacketCmdt:
          structure: TOLABAddPacketCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
        TOLABEnableOutputCmdt:
          structure: TOLABEnableOutputCmdt
          cfe_mid: '0x1880'
          cmd_code: 6
        TOLABNoArgsCmdt:
          structure: TOLABNoArgsCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
        TOLABRemovePacketCmdt:
          structure: TOLABRemovePacketCmdt
          cfe_mid: '0x1200'
          cmd_code: 0  
              
      telemetry_data:
        CFEESOneAppTlm:
          cfe_mid: '0x80B'
          topic_name: /cfe_es_one_app_tlm
        CFEESMemStatsTlm:
          cfe_mid: '0x810'
          topic_name: /cfe_es_mem_stats_tlm
        CFEESHousekeepingTlm:
          cfe_mid: '0x800'
          topic_name: /cfe_es_hk_tlm
        CFEEVSLongEventTlm:
          cfe_mid: '0x808'
          topic_name: /cfe_evs_long_event_tlm
        CFEEVSHousekeepingTlm:
          cfe_mid: '0x801'
          topic_name: /cfe_evs_hk_tlm
        CFEEVSShortEventTlm:
          cfe_mid: '0x809'
          topic_name: /cfe_evs_short_event_tlm
        CFESBHousekeepingTlm:
          cfe_mid: '0x803'
          topic_name: /cfe_sb_hk_tlm
        CFESBStatsTlm:
          cfe_mid: '0x80A'
          topic_name: /cfe_sb_stats_tlm
        CFESBAllSubscriptionsTlm:
          cfe_mid: '0x80D'
          topic_name: /cfe_sb_all_subscriptions_tlm
        CFESBSingleSubscriptionTlm:
          cfe_mid: '0x80E'
          topic_name: /cfe_sb_single_subscription_tlm
        CFETBLHousekeepingTlm:
          cfe_mid: '0x804'
          topic_name: /cfe_tbl_hk_tlm
        CFETBLTableRegistryTlm:
          cfe_mid: '0x80C'
          topic_name: /cfe_tbl_table_registry_tlm
        CFETIMEHousekeepingTlm:
          cfe_mid: '0x805'
          topic_name: /cfe_time_hk_tlm
        CFETIMEDiagnosticTlm:
          cfe_mid: '0x806'
          topic_name: /cfe_time_diagnostic_tlm

