# cFE NAME: ES APP Tlm
# FILE: cfe-es-app-tlm.txt
int32 seq
string name
string entrypoint
string filename
uint32 stacksize
uint32 moduleid
uint32 addressesarevalid
uint32 codeaddress
uint32 codesize
uint32 dataaddress
uint32 datasize
uint32 bssaddress
uint32 bsssize
uint32 startaddress
uint16 exceptionaction
uint16 priority
uint32 maintaskid
uint32 executioncounter
string maintaskname
uint32 numofchildtasks
