# cFE NAME: SB HK Tlm
# FILE: cfe-sb-hk-tlm.txt
int32 seq
uint8 command_counter
uint8 error_counter
uint8 nosubscriberscounter
uint8 msgsenderrorcounter
uint8 msgreceiveerrorcounter
uint8 internalerrorcounter
uint8 createpipeerrorcounter
uint8 subscribeerrorcounter
uint8 pipeoptserrorcounter
uint8 duplicatesubscriptionscounter
uint16 spare2align
uint16 pipeoverflowerrorcounter
uint16 msglimiterrorcounter
uint32 mempoolhandle
uint32 meminuse
uint32 unmarkedmem
