# cFE NAME: TBL HK Tlm
# FILE: cfe-tbl-hk-tlm.txt
int32 seq
uint8 command_counter
uint8 error_counter
uint16 num_tables
uint16 num_load_pending
uint16 validation_cnt
uint32 last_valid_crc
uint32 last_valid_status
uint8 active_buffer
string last_valid_tbl
uint8 success_count
uint8 failed_count
uint8 num_requests
uint8 num_free_bufs
uint8 pad1
uint16 pad2
uint32 mem_pool_hdl
uint32 last_upd_secs
uint32 last_upd_subs
string last_upd_table_name
string last_file_loaded
string last_file_dumped
string lasttableloaded
