# cFE NAME: TIME DIAG Tlm 2
# FILE: cfe-time-diag-tlm2.txt
int32 seq
uint32 tonesignalcounter
uint32 tonedatacounter
uint32 toneintcounter
uint32 toneinterrorcounter
uint32 tonetaskcounter
uint32 versioncounter
uint32 localintcounter
uint32 localtaskcounter
uint32 virtualmet
uint32 minelapsed
uint32 maxelapsed
uint32 maxlocalclock_seconds
uint32 maxlocalclock_subseconds
uint32 toneoverlimit
uint32 toneunderlimit
uint32 datastorestatus
