#!/usr/bin/env python3
import re

# Class to hold an entry in the fields table of the database generated by juicer.
class JuicerFieldEntry():

    def __init__(self, myid, symbol, name, byte_offset, mytype, little_endian, bit_size, bit_offset):
        self.myid = myid
        self.symbol = symbol
        self.name = name
        self.byte_offset = byte_offset
        self.mytype = mytype
        self.little_endian = little_endian
        self.bit_size = bit_size
        self.bit_offset = bit_offset
        self.ros_name = generateRosFieldName(name)
        self.type_symbol = None

    def getName(self):
        return self.name

    def getSymbol(self):
        return self.symbol

    def getId(self):
        return self.myid

    def getType(self):
        return self.mytype

    def getROSName(self):
        return self.ros_name

    def getByteOffset(self):
        return self.byte_offset

    def getBitOffset(self):
        return self.bit_offset

    def getTypeName(self):
        symbol = self.type_symbol
        if symbol.getAlternative():
            symbol = symbol.getAlternative()
        return symbol.getROSName()

    def setTypeSymbol(self, symbol):
        self.type_symbol = symbol

    def getTypeSymbol(self):
        symbol = self.type_symbol
        if symbol.getAlternative():
            symbol = symbol.getAlternative()
        return symbol

def generateRosFieldName(name):
    retval = name

    if any(ele.isupper() for ele in name):
        n = name
        # handle strings of caps - change them to one cap followed by lowercase
        # so that it will be one "word" in final result
        callback = lambda pat: pat.group(0).capitalize()
        n = re.sub(r'[A-Z](?:[A-Z]*(?![a-z]))', callback, n)
        # split into list of words by capital letters
        w = re.findall('([A-Z][a-z]*)', n)
        # combine all words with underscore between them
        retval = '_'.join(w)
        # return value as lower case string
        retval = retval.lower()
    else:
        n = name
        # make sure doesn't start or end with '_'
        if n.startswith("_"):
            retval = n.strip("_")
            #print("Updated field name " + retval)
        
    return retval
