cfe_msg_converter:
  ros__parameters:
    plugin_params:
#      juicer_db: ["src/cfe_ros2_bridge_plugin/cfe_plugin/resource/cfs_bootes-rc1-dev83_TL.sqlite"]
      juicer_db: ["/code/juicer/dbs/rover_all.sqlite"]      
      map_ros_name: ["src/cfe_ros2_bridge_plugin/cfe_msg_converter/config/map_ros_name.yaml"]
