cfe_msg_converter:
  ros__parameters:
    plugin_params:
      juicer_db: ["src/cfe_ros2_bridge_plugin/cfe_plugin/resource/cfs_bootes-rc1-dev83_TL.sqlite"]
      map_ros_name: ["src/cfe_ros2_bridge_plugin/cfe_msg_converter/config/map_ros_name.yaml"]
